create database employee;

CREATE TABLE EMPLOYEE(
FNAME VARCHAR(10),
MINIT CHAR(2),
LNAME VARCHAR(10),
SSN INT PRIMARY KEY,
BDATE date,
SEX VARCHAR(1),
SALARY INT,
ADDRESS VARCHAR(20),
SUPERSSN INT,
DNO INT,
);

CREATE TABLE DEPARTMENT(
DNAME VARCHAR(10),
DNUMBER INT PRIMARY KEY,
MGRSSN INT,
MGRSTARTDATE DATE,
);

CREATE TABLE DEPT_LOCATIONS(
DNUMBER INT,
DLOCATION VARCHAR(10),
PRIMARY KEY(DNUMBER,DLOCATION)
);

CREATE TABLE PROJECT(
PNAME VARCHAR(10),
PNUMBER INT,
PLOCATION VARCHAR(10),
DNUM INT,
PRIMARY KEY(PNUMBER)
);

CREATE TABLE WORKS_ON(
ESSN INT,
PNO INT,
HOURS DOUBLE,
PRIMARY KEY(ESSN,PNO)
);

CREATE TABLE DEPENDENT(
ESSN INT,
DEPENDENT_NAME VARCHAR(10),
SEX VARCHAR(1),
BDATE DATE,
RELATIONSHIP VARCHAR(10),
PRIMARY KEY(ESSN,DEPENDENT_NAME)
);

ALTER TABLE EMPLOYEE
ADD foreign key (DNO) REFERENCES DEPARTMENT(DNUMBER);

ALTER TABLE DEPARTMENT
ADD foreign key (MGRSSN) REFERENCES EMPLOYEE(SSN);

ALTER TABLE DEPT_LOCATION
ADD foreign key(DNUMBER,DLOCATION) references DEPARTMENT(DNUMBER);




ALTER TABLE WORKS_ON
ADD foreign key(ESSN,PNO) references project(PNUMBER);

ALTER TABLE WORKS_ON add
foreign key(ESSN,PNO) REFERENCES EMPLOYEE(SSN);

ALTER TABLE PROJECT
ADD foreign key(DNUM) REFERENCES DEPARTEMENT(DNUMBER);


ALTER TABLE DEPENDENT
ADD foreign key(ESSN) REFERENCES EMPLOYEE(SSN);
 
ALTER TABLE DEPARTMENT
DROP foreign key department_ibfk_1;

ALTER TABLE PROJECT
ADD foreign key(DNUM) REFERENCES DEPARTEMENT(DNUMBER);

select * from project;

drop database employee;

alter table employee
add foreign key(DNO) references department(DNUMBER);

alter table dept_locations 
drop foreign key dept_locations_ibfk_2;
